run:
  timeout: 4m
issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  format: line-number
  print-issued-lines: false
linters:
  enable:
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - gocyclo
    - gocritic
    - godot
    - gofmt
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nestif
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - staticcheck
    - testpackage
    - typecheck
    - unused
    - whitespace
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 25
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - whyNoLint
      - wrapperFunc
      - docStub
      - paramTypeCombine
      - unnamedResult
      - sloppyReassign
      - commentedOutCode
      - hugeParam
