version: "3"
# networks:
#   gw_internal:
#     external: true

services:
  backend:
    platform: linux/amd64
    image: docker.io/brisouamaury/gateway-test-service
    env_file:
      - .env
    ports:
      - "${BACK_LISTEN_ADDR}:${BACK_LISTEN_PORT}:${BACK_LISTEN_PORT}"
    # networks:
    #   - gw_internal
